name: "publish-npm"

on:
  workflow_dispatch:
    inputs:

jobs:
  publish-npm:
    name: Publish-NPM
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Install Protoc
        uses: arduino/setup-protoc@v1
        with:
          version: '3.19'

      - uses: actions/setup-node@v2
        with:
          node-version: '16.13'

      - name: Build Schema Library
        run: |
          mkdir -p build/js
          npm install -g ts-protoc-gen
          protoc --proto_path=. --ts_out=build/js schemas/*.proto

      - name: Publish to NPM
        uses: JS-DevTools/npm-publish@v1
        with:
          token: ${{ secrets.NPM_KEY }}
